# TODO: Metadata
name:                chesserole
version:             0.1.0.0
#github:              "WhistlePayer/chesserole" # TODO: publish
license:             BSD3
author:              "Joshua Price"
maintainer:          "joshprice247@gmail.com"
copyright:           "Copyright (c) 2018, Joshua Price"

extra-source-files:
- README.md
- ChangeLog.md
- assets/*

# TODO: Metadata used when publishing your package
#synopsis:            Short description of your package
category:            Game

#description:         Please see the README on GitHub at <https://github.com/WhistlePayer/chesserole#readme> # TODO

ghc-options:
- -Wall

dependencies:
- base >= 4.7 && < 5
- mtl # TODO: Bounds
- sdl2 # TODO: Bounds
- sdl2-image # TODO: Bounds
- linear # TODO: Bounds
- typed-process # TODO: Bounds

library:
  source-dirs: src

executables:
  chesserole:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chesserole

tests:
  chesserole-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chesserole
