resolver: lts-13.6

packages:
- .

# Building with nix *should* work on NixOS but won't on other Systems due to:
# <https://github.com/NixOS/nixpkgs/issues/9415>
nix:
  packages:
  - SDL2
  - SDL2_image
  - stockfish